### ISSUE TITLE
Typo in nexus example file

### ISSUE THREAD

**Issue by santiagosnchez** [BEAST2-Dev/beast-geo#6]
Just wanted to point out that there is a typo in the `#NEXUS` header of the `GEO_SPHERE` example nexus file. It reads `#NEXSUS` instead of `#NEXUS`. While it reads well in BEAST2, BEAST1 does not recognize the file formate unless you change it to `#NEXUS`.

**Comment by rbouckaert** [comment]
Fixed by 8f3ecfb249768a143431bc992847cf89df531d4d
