### ISSUE TITLE
HeatMapMaker option to change colour range 

### ISSUE THREAD

**Issue by rbouckaert** [BEAST2-Dev/beast-geo#7]
inspired by [CompEvol/beast2#835](https://github.com/CompEvol/beast2/issues/835)
Also, update the tutorial with HeatMapMaker the latest inputs.

**Comment by rbouckaert** [comment]
x

**Comment by rbouckaert** [comment]
Fixed by 2e31fe4efcb4887712af6bb38e22d24324e9b165

Tutorial is updated, available here:
https://github.com/BEAST2-Dev/beast-geo/releases/download/v1.2.0/phylogeography_s.pdf

**Comment by carolynzy** [comment]
@rbouckaert Thank you! That was a quick response! But I ran into this error when trying the new version:
```
Loading background image C:\Users\carol\Documents\worldmap10.png
java.io.FileNotFoundException: \tmp\bg.png (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
	at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at sphericalGeo.util.HeatMapMaker.run(Unknown Source)
	at sphericalGeo.util.HeatMapMaker.main(Unknown Source)
No mask image
translation map size = 15
Parsing trees D:\Documents\WGS\beast_xml\420_complex3.tree ...  done
Drawing dots...
|=========|=========|=========|=========|=========|=========|=========|=========|=========|=========|

done
Writing file C:\Users\carol\Documents\complex3_geo.png done
Writing legend C:\Users\carol\Documents\\legend.png  done in 2 seconds
All done
```
The "Bounding Box" option doesn't work this time. And the color of the legend is not updated as the color of dots.

**Comment by rbouckaert** [comment]
@carolynzy thanks for reporting these bugs -- I think they should be fixed now and updated the release. Can you try the following: uninstall GEO_SPHERE, then install GEO_SPHERE again and let me know if the problems persists (or any other problem pops up). Thanks, Remco

**Comment by carolynzy** [comment]
@rbouckaert That was quick! Thank you. This time the "Bounding Box" is working well. But I still got the same error message and the color of legend is not changing.

**Comment by carolynzy** [comment]
@rbouckaert I found that if I change the "Color Range" to 0.8, then it works perfectly well! Though the error message is still there, it seems not interfering with the result.

**Comment by rbouckaert** [comment]
@carolynzy thanks for the feedback -- the error message was created by some debugging code, which is now removed. Let me know if you run into any more problems.
